### ISSUE TITLE
Editorial: Capital letter equivalents for bicameral scripts

### ISSUE THREAD

**Issue by r12a** [w3c/uievents#123]
5.1.1. Key Legends
https://w3c.github.io/uievents/#key-legends

> For historical reasons, the character keys are typically marked with the capital-letter equivalents of the character value they produce, e.g., the G key (the key marked with the glyph "G"), will produce the character value "g" when pressed without an active modifier key (e.g., Shift) or modifier state (e.g., CapsLock).

Editorial: To be more accurate it may be better to say:

For historical reasons, on keyboards for bicameral scripts, the character keys are typically marked with the capital-letter equivalents...

I don't actually know whether this is true for all such scripts. May be worth a quick check. That would include keyboards for languages using Latin, Greek, Cyrillic, Armenian, Cherokee, Adlam.

(Less common bicameral scripts include Coptic, Warang Citi, Old Hungarian, Osage, Glagolitic and Deseret.

**Comment by asmusf** [comment]
Then we have scripts like Cherokee, Georgian and also Hiragana/Katakana where the keys may be marked with one version of a series of parallel scripts (Cherokee is intended to be bicameral, but isn't supported the same way as other scripts in Unicode because of the late addition of the other case).

Perhaps better to simply say: "Sometimes the image on the key cap is not what you get when pressing a key in the unshifted state" and give a single! example rather than trying to make a general statement that's bound to run into some edge case.
