### ISSUE TITLE
Need 'Unspecified' value for KeyboardEvent.code

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#20]
The current spec doesn't define an 'Unspecified' value that can be used when the code value cannot be determined.

Having a separate value is important to be able to distinguish between 'not implemented' and 'implemented, but unable to determine code'.

Currently, we define 'Unspecified' for 'key', but don't have the equivalent text for 'code'.

**Comment by masayuki-nakano** [comment]
There are 3 cases of empty code value under current spec:

1. The platform tells UAs a valid scancode or something but proper value for it isn't defined
2. The platform does not tell valid scancode or anything.
3. The key is caused by virtual keyboard or something non-physical keyboard.

It may be impossible to distinguish #2 and #3 if they causes same scancode or something, though. So, only #1 case could cause specific value?

**Comment by garykac** [comment]
This issue was moved to w3c/DOM-Level-3-Events-code#3
