### ISSUE TITLE
Specification status report for TPAC 2019

### ISSUE THREAD

**Issue by LJWatson** [w3c/uievents#242]
Please can you respond to this comment with a brief specifications status report for the WebApps meeting at TPAC. The report should address the following:
* What progress has your spec made in the last 12 months?
* Is anything blocking your spec from moving to CR?
* If yes, what is your plan to unblock it and do you need any help?
* What do you want to achieve for your spec in the next two days (of breakout sessions)?

We're tracking these status reports in [WebApps issue #19](https://github.com/w3c/webappswg/issues/19)

Thanks.

**Comment by marcoscaceres** [comment]
@garykac or @travisleithead, any chance of an update?

**Comment by travisleithead** [comment]
I haven't been particularly engaged in this effort for awhile; hoping Gary can provide an update...

**Comment by garykac** [comment]
Sorry for responding so late with this. Here is the current status.

So, UIEvents is a bit of an odd spec since we're not adding new features,
but rather trying to properly document existing implementations.

As it stands, the UI Events spec is written in a very old informal style
and will not be accepted to move up to CR. I am working to address this by
modernizing the spec (to make it more algorithmic), but progress has been
slow.

I tried to advance some of these issues during the last TPAC, but due to a
scheduling conflict (grrr...) the discussion was placed opposite a timeslot
where many relevant participants could not attend. Because of that we only
had a limited (but still useful) discussion. Also, I have been able to work
on this far less that I wanted to over the past year, and I apologize for
this.

To unblock this, I plan on (once again) proposing breakout sessions to
discuss the issues that need to be included in these algorithmic
descriptions. For example, I know that hit testing needs to involve some
CSS experts so that it integrates appropriately with rounded corners, and
so on. There are many areas where I am not a domain expert and need to hook
up with them to describe the process adequately.

Ideally, I would like to:

   - Schedule Wednesday breakout sessions to discuss one or two of these
   topics in detail (I suggest Mouse (move, click, ...) and Focus as a
   starting point.
   - Make sure that the relevant domain experts are present to walk through
   the issues (<- this is the hard part and where I would like help)
   - Coordinate with Marco/Leonie for the best approach to make these
   updates to the spec. This will be an iterative process, so I think I'll
   need to work in side documents until they reach a certain level of
   maturity, but I'm open to other suggestions.

In addition, there is also the UI Events Key and Code specs, which need to
be Level 1 and Level 2 so that we can say that all implementations must
support Level 1 while Level 2 is optional. During TPAC, I would like to get
general agreement on these levels so that we can advance these
specifications. I would also like to discuss the process for updating these
specs when new keys are proposed.

-Gary
