### ISSUE TITLE
Define inputType "insertFromPasteAsQuotation"

### ISSUE THREAD

**Issue by zcorpan** [w3c/uievents#368]
See https://github.com/w3c/uievents/pull/362/files#r1458215548

Gecko supports "insertFromPasteAsQuotation" in addition to "insertFromPaste".

cc @masayuki-nakano

**Comment by masayuki-nakano** [comment]
It's already been defined by Input Events.
https://w3c.github.io/input-events/#interface-InputEvent-Attributes

**Comment by garykac** [comment]
A problem is that people may expect those attributes to be defined in UI Event because that's where the core event is located.

As part of the proposal to split up UI Events, we would create a separate "UIEvents-Input" spec, and then (once it was stabilized) we would likely merge that spec with the spec called InputEvents.
