### ISSUE TITLE
Need to remove input/beforeinput event info from D3E and point to input event spec

### ISSUE THREAD

**Issue by garykac** [w3c/uievents#38]
Copied from W3C Bugzilla: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27827

##### Gary Kacmarcik 2015-01-14 01:29:41 UTC
Current (placeholder) spec is at: http://w3c.github.io/editing-explainer/input-events.html

We need to remove our input/beforeinput info and refer to this spec where appropriate.

##### Comment 1 Gary Kacmarcik 2015-01-26 04:33:48 UTC
Sections removed in https://dvcs.w3.org/hg/dom3events/rev/5bcdc56bc48c

Waiting for official spec link to fix up references to new spec.

##### Comment 2 Arthur Barstow 2015-03-21 15:11:59 UTC
Bulk move of all D3E bugs to the UI Events component.

##### Comment 3 Rick Byers 2015-07-23 17:40:22 UTC
Any update?  It's really confusing for the UI Events spec to mention beforeinput/input and InputEvent but for the links to just go nowhere.  Took me quite awhile to find https://w3c.github.io/editing/input-events.html.

**Comment by masayuki-nakano** [comment]
Even if input/beforeinput events will be defined in editing API, UIEvents should explain:

Web apps shouldn't use keydown, keypress, keyup event nor compositionupdate event to catch a text input. Use input or beforeinput event for such purpose since keyboard events may not be fired with a composition, keyboard events must not be fired with text input without keyboard such as speech input. Similarly, compositionupdate cannot catch text inputs from keyboard without IME.

This is what a lot of web developers don't understand well.

**Comment by garykac** [comment]
`beforeinput` and `input` have been moved back into the UIEvents spec.
