### ISSUE TITLE
Use https://rawgit.com URL for Keyboard Event Viewer

### ISSUE THREAD

**Issue by choniong** [w3c/uievents#72]
The change to `beforeinput` is not reflected in https://cdn.rawgit.com/w3c/uievents/gh-pages/tools/key-event-viewer.html

According to [Rawgit](https://rawgit.com/) `https://cdn.rawgit.com` should be used for production
> It's best to use a specific tag or commit hash in the URL (not a branch). Files are cached permanently after the first request.

**Comment by garykac** [comment]
https://cdn.rawgit.com/w3c/uievents/gh-pages/tools/key-event-viewer.js shows the latest version of the code.

The cache is your local cache and you can disable it by opening Chrome's DevTools and refreshing the page (you may have to enable to "Disable cache" option.

We don't want to use the repo-tagged version because then we would need to update the link every time we updated the code.
