### ISSUE TITLE
4.1 and 4.9 keypress is deprecated

### ISSUE THREAD

**Issue by LJWatson** [w3c/uievents#96]
From the <a href="https://lists.w3.org/Archives/Public/public-apa/2016Jun/0055.html">June 2016 APA review</a> by @cyns.

Keypress is deprecated. This is because there wasn’t implementation. Even though this feels most parallel to click, keydown is more widely supported. I
think this is ok, given the implementation issues.

**Comment by garykac** [comment]
I'll add "(if supported)" after mentions of `keypress` in spec since we still describe it in the legacy appendix and it's sometimes useful to have `keypress` present (e.g., in the event firing order tables).

Notes:
(1) There is no section 4.9. I assume this was intended for sections 5 and 6.
(2) `keypress` was not deprecated because of a lack of implementations (all browsers generate `keypress`). It was deprecated because its use case was subsumed by `beforeinput`, which is a more general way of detecting when the user has produced input that can affect the DOM.

**Comment by garykac** [comment]
Minor update: Original comment in [APA review](https://lists.w3.org/Archives/Public/public-apa/2016Jun/0055.html) was for "4.1 and 9" and based on bug #102, '9' appears to mean Appendix C (which covers legacy events).
